apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub
spec:
  selector:
    matchLabels:
      app: pubsub
  replicas: 1 
  template: 
    metadata:
      labels:
        app: pubsub
    spec:
      containers:
      - name: dotnetworld
        image: pubsub/petsmart:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: pubsub
spec:
 type: NodePort
 selector:
   app: pubsub
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32080
 selector:
   app: pubsub